### ISSUE TITLE
inference code is use i-2K frames to predict i  but （-K to K） frames is used in paper，why difference？

### ISSUE THREAD

**Issue by dlongry** [msracver/Flow-Guided-Feature-Aggregation#19]

**Comment by dlongry** [comment]
OK，I misunderstanding the code，thanks for your work

**Comment by Feywell** [comment]
@dlongry How to understand the way of using frames in code. I have the puzzle as you.
Can you tell us details?

**Comment by dlongry** [comment]
You should see the "get_aggregation_symbol" function in the "\fgfa_rfcn\symbols\resnet_v1_101_flownet_rfcn.py": such as line 1057 ， use `cur_data = mx.symbol.slice_axis(data_cache, axis=0, begin=cfg.TEST.KEY_FRAME_INTERVAL, end=cfg.TEST.KEY_FRAME_INTERVAL+1) ` to get middle frame to detect。 @Feywell

**Comment by Feywell** [comment]
@dlongry Thank you. So, it means it use frames from -k to k as paper.
