### ISSUE TITLE
Difference between the imagenet_vid_eval and imagenet_vid_eval_motion results?

### ISSUE THREAD

**Issue by HaydenFaulkner** [msracver/Flow-Guided-Feature-Aggregation#24]
Hi

I was just wondering the difference in the mAP@0.5 scores for the two files. So in the imagenet_vid_eval you get classwise AP but when all these are averaged we only get 0.6351 but then the mAP from the eval_motion script gives 0.7711. I assume there is some conceptual difference in how the scores are calculated/averaged?

Update: Fixed, it was an issue with the detections I was using.

Thanks,
Hayden

**Comment by Feywell** [comment]
@HaydenFaulkner How can you use imagenet_vid_eval to get classwise AP?
Can you tell me details?
Thank you!
