### ISSUE TITLE
Motion IoU calculation

### ISSUE THREAD

**Issue by hellock** [msracver/Flow-Guided-Feature-Aggregation#4]
Thanks for releasing the code. How is motion iou calculated when the length of object instance is less than 10 frames?

**Comment by einsiedler0408** [comment]
@hellock We simply average the IoUs over the length of object instance when it is less than 10.

**Comment by hellock** [comment]
I may have misunderstood the motion metric. It's not calculated as `mean(iou(t, t-10), iou(t, t+10))`, but `mean(iou(k, k+1) for k in [t-10, t+10))`, right?

**Comment by einsiedler0408** [comment]
It's ```mean(iou(t, k) for k in (t-10, t+10))```. In case that objects may have periodic motion, calculating iou frame-by-frame may not be appropriate.

**Comment by hellock** [comment]
Get it, thank you!
