### ISSUE TITLE
Question about Imagesets

### ISSUE THREAD

**Issue by KevinQian97** [msracver/Flow-Guided-Feature-Aggregation#55]
Hi, sorry for bothering.

I am a little bit confused about your imagesets folder.
I download both DET and VID dataset and my ImageSets folder looks lke:

--ImageSets
----DET
------train_XX.txt
----VID
------train_XX.txt

which seems different from yours.(like DET_train_30classes.txt)

So would you mind directly share your imagesets?

Thanks

**Comment by KevinQian97** [comment]
Sorry I just mis-delete your imagenet folder. You can close the issue.

Thanks,

**Comment by Sanku-Yogesh** [comment]
Hey, where did u download the dataset? could u please refer to this comment https://github.com/Scalsol/mega.pytorch/issues/73#issue-754884469
