### ISSUE TITLE
Cannot git check v0.10.0

### ISSUE THREAD

**Issue by plaovem** [msracver/Flow-Guided-Feature-Aggregation#6]
Hi, the v0.10.0 seems have been deleted. So, I git check v0.10.0-support, but I cannot run the demo. Could you help me to solve it, please?

**Comment by plaovem** [comment]
Ok, I have solved it. Just checkout the master branch. The master version has include the PSROIpooling. Another thing is that the line 1083 in resnet_v1_flownet_rfcn.py in wrong. You cannot use += for symbol variable. Just change into aggregated_conv_feat + tiled_weight * warp_list[i]. Then, it works.

Seems the new version MXNET change the rules for programing!

**Comment by kampelmuehler** [comment]
`git checkout v0.10.0` worked here on ubuntu 16.04 without any issues
